#!/run/current-system/sw/bin/bash
if [[ "$1" == "--now" ]]; then
  :
else
  sleep 1
fi

# get a random wallpaper from the wallpapers directory
wallpaper=$(find /home/hackr/walls -type f -name "*.jpg" | shuf -n 1)

nohup awww img -t random $wallpaper 2>&1 > /dev/null &

# TODO: remove this once niri adopts true blur
sleep 3
niri msg action load-config-file

disown
