format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$fill\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$conda\
$python\
$time\n  \
[󱞪](fg:iris) \
"""

palette = "oscura-midnight"

[palettes.oscura-midnight]
overlay = '#232323'
overlayd = '#161616'
overlaydd = '#0b0b0f'
love = '#d84f68'
gold = '#f9b98c'
rose = '#e6e7a3'
pine = '#4ebe96'
foam = '#54c0a3'
iris = '#e6e7a3'

[directory]
format = "[](fg:overlayd)[ $path ]($style)[](fg:overlayd) "
style = "bg:overlayd fg:pine"
truncation_length = 5
truncation_symbol = ""
truncate_to_repo = false

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[fill]
style = "fg:overlay"
symbol = " "

[git_branch]
format = "[](fg:overlaydd)[ $symbol $branch ]($style)[](fg:overlaydd) "
style = "bg:overlaydd fg:foam"
symbol = ""

[git_status]
disabled = false
style = "bg:overlaydd fg:love"
format = '[](fg:overlaydd)([$all_status$ahead_behind]($style))[](fg:overlaydd) '
up_to_date = '[ ✓ ](bg:overlaydd fg:iris)'
untracked = '[?\($count\)](bg:overlaydd fg:gold)'
stashed = '[$](bg:overlaydd fg:iris)'
modified = '[!\($count\)](bg:overlaydd fg:gold)'
renamed = '[»\($count\)](bg:overlaydd fg:iris)'
deleted = '[✘\($count\)](style)'
staged = '[++\($count\)](bg:overlaydd fg:gold)'
ahead = '[⇡\(${count}\)](bg:overlaydd fg:foam)'
diverged = '⇕[\[](bg:overlaydd fg:iris)[⇡\(${ahead_count}\)](bg:overlaydd fg:foam)[⇣\(${behind_count}\)](bg:overlaydd fg:rose)[\]](bg:overlaydd fg:iris)'
behind = '[⇣\(${count}\)](bg:overlaydd fg:rose)'

[time]
disabled = false
format = "[](fg:overlay)[ $time 󰴈 ]($style)[](fg:overlay)"
style = "bg:overlay fg:rose"
time_format = "%I:%M%P"
use_12hr = true

[username]
disabled = false
format = "[](fg:overlay)[ 󰧱 $user ]($style)[](fg:overlay) "
show_always = true
style_root = "bg:overlay fg:iris"
style_user = "bg:overlay fg:iris"

[hostname]
disabled = false
format = "[](fg:overlayd)[   $hostname ]($style)[](fg:overlayd) "
style = "bg:overlayd fg:iris"
ssh_only = false

# Languages

[c]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[elixir]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[elm]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[golang]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[haskell]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[java]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[julia]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[nodejs]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = "󰎙 "

[nim]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = "󰆥 "

[rust]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = ""

[scala]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[python]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = ' '

[conda]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$environment]($style)[](fg:overlay) "
disabled = false
symbol = '🅒 '