{
  pkgs,
  inputs,
  lib,
  ...
}: {
  nixpkgs.overlays = [
    inputs.nix-vscode-extensions.overlays.default
  ];
  programs.vscode = {
    profiles.default.extensions = with pkgs.vscode-marketplace;
      [
        # add extensions here
        aaron-bond.better-comments
        adpyke.vscode-sql-formatter
        alefragnani.project-manager
        antfu.goto-alias
        arrterian.nix-env-selector
        astro-build.astro-vscode
        bierner.github-markdown-preview
        bierner.markdown-checkbox
        bierner.markdown-emoji
        bierner.markdown-footnotes
        bierner.markdown-mermaid
        bierner.markdown-preview-github-styles
        bierner.markdown-yaml-preamble
        biomejs.biome
        bradlc.vscode-tailwindcss
        codezombiech.gitignore
        dbaeumer.vscode-eslint
        digitalbrainstem.javascript-ejs-support
        dlasagno.rasi
        docker.docker
        donjayamanne.git-extension-pack
        donjayamanne.githistory
        dotjoshjohnson.xml
        dustypomerleau.rust-syntax
        eamodio.gitlens
        editorconfig.editorconfig
        esbenp.prettier-vscode
        fey.oscura
        fill-labs.dependi
        foxundermoon.shell-format
        geequlim.godot-tools
        github.vscode-github-actions
        golang.go
        hashicorp.terraform
        irongeek.vscode-env
        jeroen-meijer.shibuya
        jnoortheen.nix-ide
        jonkwheeler.styled-components-snippets
        kdl-org.kdl-v1
        knisterpeter.vscode-commitizen
        leonardssh.vscord
        me-dutour-mathieu.vscode-github-actions
        mechatroner.rainbow-csv
        mkhl.direnv
        ms-azuretools.vscode-containers
        ms-azuretools.vscode-docker
        ms-dotnettools.csharp
        ms-vscode-remote.remote-containers
        ms-vscode-remote.remote-ssh
        ms-vscode-remote.remote-ssh-edit
        ms-vscode.hexeditor
        ms-vscode.remote-explorer
        ms-vsliveshare.vsliveshare
        pinage404.nix-extension-pack
        polymeilex.rust-targets
        prisma.prisma
        redhat.java
        redhat.vscode-xml
        redhat.vscode-yaml
        rust-lang.rust-analyzer
        ryanluker.vscode-coverage-gutters
        sourcegraph.amp
        styled-components.vscode-styled-components
        svelte.svelte-vscode
        unifiedjs.vscode-mdx
        usernamehw.errorlens
        vscjava.vscode-gradle
        vscjava.vscode-java-debug
        vscjava.vscode-java-dependency
        vscjava.vscode-java-pack
        vscjava.vscode-java-test
        vscjava.vscode-maven
        vue.volar
        yanfeixin.king-trae-icon
        yoavbls.pretty-ts-errors
        ziglang.vscode-zig
        ziyasal.vscode-open-in-github
        znck.vue
      ]
      ++ (with pkgs.open-vsx; [
        ])
      ++ (with pkgs.vscode-extensions; [
        ms-vscode.cpptools
        ms-vscode.cpptools-extension-pack
      ])
      ++ (with pkgs.vscode-extensions; [
        ms-vscode.live-server
        vadimcn.vscode-lldb
        tamasfe.even-better-toml
      ]);
  };
}
