{ pkgs, inputs, lib, ... }:
{
  nixpkgs.overlays = [
    inputs.nix-vscode-extensions.overlays.default
    inputs.nix4vscode.overlays.forVscode
  ];
  nixpkgs.config.allowUnsupportedSystem = true;
  programs.vscode = {
    profiles.default.extensions =
      with pkgs.vscode-marketplace;
      [
        # add extensions here
        angular.ng-template
        idleberg.applescript
        astro-build.astro-vscode
        njpwerner.autodocstring
        boto3typed.boto3-ide
        ms-azuretools.vscode-azurefunctions
        ms-azure-devops.azure-pipelines
        ms-azuretools.vscode-azureresourcegroups
        ms-azuretools.vscode-azurestaticwebapps
        ms-azuretools.vscode-azurevirtualmachines
        jeff-hykin.better-cpp-syntax
        aaron-bond.better-comments
        biomejs.biome
        danielpinto8zz6.c-cpp-compile-run
        xaver.clang-format
        twxs.cmake
        josetr.cmake-language-support-vscode
        ms-vscode.cmake-tools
        ms-azuretools.vscode-containers
        marus25.cortex-debug
        ryanluker.vscode-coverage-gutters
        mcu-debug.debug-tracker-vscode
        vscjava.vscode-java-debug
        fill-labs.dependi
        ms-vscode-remote.remote-containers
        plorefice.devicetree
        mkhl.direnv
        leonardssh.vscord
        ms-azuretools.vscode-docker
        docker.docker
        cschlosser.doxdocgen
        editorconfig.editorconfig
        digitalbrainstem.javascript-ejs-support
        irongeek.vscode-env
        usernamehw.errorlens
        dbaeumer.vscode-eslint
        vscjava.vscode-java-pack
        donjayamanne.git-extension-pack
        donjayamanne.githistory
        github.vscode-github-actions
        me-dutour-mathieu.vscode-github-actions
        bierner.github-markdown-preview
        codezombiech.gitignore
        eamodio.gitlens
        dtoplak.vscode-glsllint
        circledev.glsl-canvas
        golang.go
        geequlim.godot-tools
        antfu.goto-alias
        vscjava.vscode-gradle
        hashicorp.terraform
        ms-vscode.hexeditor
        mohd-akram.vscode-html-format
        visualstudioexptteam.vscodeintellicode
        visualstudioexptteam.intellicode-api-usage-examples
        ms-python.isort
        kdl-org.kdl-v1
        ciantic.keymapceditor-vsc
        redhat.java
        james-yu.latex-workshop
        ms-vsliveshare.vsliveshare
        llvm-vs-code-extensions.lldb-dap
        ms-vscode.makefile-tools
        bierner.markdown-checkbox
        bierner.markdown-emoji
        bierner.markdown-footnotes
        bierner.markdown-preview-github-styles
        bierner.markdown-mermaid
        bierner.markdown-yaml-preamble
        vscjava.vscode-maven
        unifiedjs.vscode-mdx
        mcu-debug.memory-view
        ms-vscode.mono-debug
        william-voyek.vscode-nginx
        ahmadalli.vscode-nginx-conf
        raynigon.nginx-formatter
        bbenoist.nix
        arrterian.nix-env-selector
        pinage404.nix-extension-pack
        jnoortheen.nix-ide
        brettm12345.nixfmt-vscode
        nordic-semiconductor.nrf-kconfig
        nuxtr.nuxtr-vscode
        ziyasal.vscode-open-in-github
        fey.oscura
        mcu-debug.peripheral-viewer
        ms-vscode.powershell
        esbenp.prettier-vscode
        yoavbls.pretty-ts-errors
        prisma.prisma
        alefragnani.project-manager
        vscjava.vscode-java-dependency
        ms-python.vscode-pylance
        ms-python.python
        ms-python.debugpy
        donjayamanne.python-environment-manager
        teticio.python-envy
        tushortz.python-extended-snippets
        donjayamanne.python-extension-pack
        kevinrose.vsc-python-indent
        mgesbert.python-path
        zeshuaro.vscode-python-poetry
        bbenoist.qml
        delgan.qml-format
        theqtcompany.qt-cpp
        theqtcompany.qt-core
        theqtcompany.qt
        theqtcompany.qt-qml
        theqtcompany.qt-ui
        mechatroner.rainbow-csv
        dlasagno.rasi
        ms-vscode-remote.remote-ssh
        ms-vscode-remote.remote-ssh-edit
        ms-vscode.remote-explorer
        mcu-debug.rtos-views
        jscearcy.rust-doc-viewer
        dustypomerleau.rust-syntax
        polymeilex.rust-targets
        rust-lang.rust-analyzer
        techtheawesome.rust-yew
        gencer.html-slim-scss-css-class-completion
        yanfeixin.king-trae-icon
        slevesque.shader
        foxundermoon.shell-format
        jeroen-meijer.shibuya
        shopify.theme-check-vscode
        adpyke.vscode-sql-formatter
        jonkwheeler.styled-components-snippets
        sysoev.language-stylus
        svelte.svelte-vscode
        swiftlang.swift-vscode
        bradlc.vscode-tailwindcss
        tauri-apps.tauri-vscode
        vscjava.vscode-java-test
        knisterpeter.vscode-commitizen
        vscode-icons-team.vscode-icons
        thenuprojectcontributors.vscode-nushell-lang
        styled-components.vscode-styled-components
        znck.vue
        vue.volar
        polymeilex.wgsl
        ggsimm.wgsl-literal
        redhat.vscode-xml
        dotjoshjohnson.xml
        redhat.vscode-yaml
        ziglang.vscode-zig
        spadin.zmk-tools
      ]
      ++ (with pkgs.open-vsx; [
        muhammad-sammy.csharp
      ])
      ++ (lib.optionals pkgs.stdenv.isLinux (with pkgs.vscode-extensions; [
        ms-vscode.cpptools
        ms-vscode.cpptools-extension-pack
      ]))
      ++ pkgs.nix4vscode.forVscode [
        "ms-dotnettools.csharp.2.63.32"
      ]
      ++ (with pkgs.vscode-extensions; [
        ms-vscode.live-server
        vadimcn.vscode-lldb
        tamasfe.even-better-toml
      ]);
  };
}