#!/run/current-system/sw/bin/bash

# get a random wallpaper from the wallpapers directory
wallpaper=$(find /home/hackr/walls -type f -name "*.jpg" | shuf -n 1)

nohup swww img $wallpaper 2>&1 > /dev/null &
disown
