#:schema https://jj-vcs.github.io/jj/prerelease/config-schema.json

[ui]
editor = "hx"

[user]
name = "Mohammad Al-Ahdal"
email = "hackr@hackr.sh"

[signing]
backend = "ssh"
key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/GcrTw0JfU8+cy19W7Y6EoC72jDGddrY2hPA7pMDR6arQpagEvQZXPbJAjV58cIOs619zVsQJdk3iTuR4Vh+s58Emn835kR/ZqL6DJBfBJYRYCFZKUIpvG4Re2ycjaGfY77ytb5AZLhqpClswgpUa7rkKK90i/NsI5a4hnFidqxQB5hxiIBHvvtr43TSpxfGIFVKejFxJKQhgHRtxWFecLyHalRQlMAbKC8880WD+pQyNOaTvl/8944ifnu8h0hEngGM28w3dWp4DbfWt/XVlWn7Od+BHazZAtokzRFTvwgvxeBDm2vWEYmBv9V4AGLgxbzcOP0dApra7+RSI4rCFwp2KL6uP1Axzr7mITg0mARmY9QMTRMCt1OFN7Lqb6eNCF7qVF0OQfhYYJRBoEb+RIFMUfolW0taAJhbGszgOYBxiQ+6UljsaiaulZSR40LkNER6RTHg7vDzx1mzSzBX8g38JxMfDzdGDyu5cHap5x6XpHCHSxmnTkOTiUPGzwGk="
behavior = "own"
backends.ssh.program = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"


[[--scope]]
--when-repositories = [ "~/work" ]
[--scope.user]
email = "mohammad@knowhistory.ca"
[--scope.signing]
key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCx+8lUKPTCZ74tG2J4kBNLffS4/hBRfYFPnK0Z9Gsb6ccoJW4rev/3jkbjZKgM1XwjBL7RVbeY7xxpIdkkX9V+TVlKvh4Saw0K5fZg+dOVwmDzIptK0SeTGju2xnXHEiuDg0/q642Go/bYZPFT5LASHSlf6lTyb1D6lz+n2+GswQbEcsQkURP27TEfEp0x82n3+bHsgnZ7JMDroQ/OHRwQkI+m88uQenvq4Oq2cgMbmqd28wu53d4Z85FoTrsFGdivTgdCR864Yz9w2VgoT2dy7NUn8MvzG0Kp9q9+DkXA4vm3PHMoi93vqU7D2kn2LSSg3CB0+MooAkgMvCSN+GhMOaFJIsGwWa/SUg7gHesB5nFnxZpi1+hSS939U3LlzTavD1gHDWO5iqvuKY+VZa6yPvyVNIc7TwzZGhyPF8OVmrD6ZR7ROdjo/PFw1EtGjDP/qDMOTN2eVZsSf1OMvdv25aDTtLoXuG/mEEmFi1VFtKdqvzfQuwZJsa4ZvAIwZVBh2GY3NsUd3ZVIGmg0RA2uU3/gLEpJFdxrlPhY+2CdBZVQ+ga0CLAs3D4fcqKjOjNbkuwvcIoYKQFskl1uqRTavsMyzBORCazx4bc6nCSyhBEaVf312/O1lRqj5bB2mtYllzP1/2aPyfjTBXj3gAOHbWynw9Z1MWrjnjiW/v+uew=="
